---
name: Code Quality Checks

on:
  push:
    branches: [main, development]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry update
      {% if cookiecutter.use_pytest == 'y' -%}
      - name: Unit & Coverage test with pytest
        run: poetry run pytest
      {% endif -%}
      {% if cookiecutter.use_flake8 == 'y' -%}
      - name: Check style with flake8
        run: poetry run flake8 {{cookiecutter.project_slug}}/ tests/ main.py
      {% endif -%}
      {% if cookiecutter.use_pylint == 'y' -%}
      - name: Check style with pylint
        run: poetry run pylint {{cookiecutter.project_slug}}/
      {% endif -%}
      {% if cookiecutter.use_black == 'y' -%}
      - name: Check format with black
        run: poetry run black --check .
      {% endif -%}
      {% if cookiecutter.use_mypy == 'y' -%}
      - name: Check type hinting with mypy
        run: poetry run mypy
      {% endif -%}
      {% if cookiecutter.use_yamllint == 'y' -%}
      - name: Check yaml style with yamllint
        run: poetry run yamllint . -c yamllint-config.yml
      {% endif -%}
