---
name: Code Quality Checks

on:
  push:
    branches: [main, development]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry update
      - name: Unit test with pytest
        run: poetry run pytest
      - name: Check style with flake8 & pylint
        run: poetry run flake8 hooks/ tests/
      - name: Check format with black
        run: poetry run black --check .
      - name: Check type hinting with mypy
        run: poetry run mypy
